-- Event Types
INSERT INTO event_types (name, slug) VALUES
('Yoga', 'yoga'),
('Healing', 'healing'),
('Therapy', 'therapy'),
('Show', 'show'),
('Theater', 'theater'),
('Music Concert', 'music-concert'),
('Dance Performance', 'dance-performance'),
('Art Exhibition', 'art-exhibition'),
('Workshop', 'workshop'),
('Retreat', 'retreat'),
('Meditation', 'meditation'),
('Sound Healing', 'sound-healing'),
('Breathwork', 'breathwork'),
('Ecstatic Dance', 'ecstatic-dance'),
('Festival', 'festival'),
('Market & Bazaar', 'market-bazaar'),
('Food & Culinary', 'food-culinary'),
('Sports & Fitness', 'sports-fitness'),
('Wellness', 'wellness'),
('Spiritual Ceremony', 'spiritual-ceremony'),
('Photography', 'photography'),
('Film Screening', 'film-screening'),
('Comedy', 'comedy'),
('Networking', 'networking'),
('Community Gathering', 'community-gathering');