-- Bali Locations
INSERT INTO locations (name, slug) VALUES
('Ubud', 'ubud'),
('Canggu', 'canggu'),
('Seminyak', 'seminyak'),
('Kuta', 'kuta'),
('Legian', 'legian'),
('Sanur', 'sanur'),
('Nusa Dua', 'nusa-dua'),
('Uluwatu', 'uluwatu'),
('Jimbaran', 'jimbaran'),
('Denpasar', 'denpasar'),
('Tabanan', 'tabanan'),
('Gianyar', 'gianyar'),
('Karangasem', 'karangasem'),
('Singaraja', 'singaraja'),
('Lovina', 'lovina'),
('Amed', 'amed'),
('Candidasa', 'candidasa'),
('Padang Bai', 'padang-bai'),
('Munduk', 'munduk'),
('Bedugul', 'bedugul'),
('Tegallalang', 'tegallalang'),
('Sidemen', 'sidemen'),
('Nusa Penida', 'nusa-penida'),
('Nusa Lembongan', 'nusa-lembongan'),
('Kintamani', 'kintamani');